# ---------------------------------------------------------
# DİKKAT: Burada tire (-) yerine ALT ÇİZGİ (_) kullanıyoruz.
# dbt kuralı: Proje isimlerinde tire yasaktır.
# ---------------------------------------------------------
name: 'my_new_project'  # <-- TİRELERİ ALT ÇİZGİ YAPTIK
version: '1.0.0'
config-version: 2

profile: 'amazon_esci'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# ---------------------------------------------------------
# MODEL AYARLARI
# Yukarıdaki 'name' ile buradaki başlık BİREBİR AYNI olmalı.
# ---------------------------------------------------------
models:
  my_new_project:

    staging:
      +materialized: view
      +schema: esci_staging

    intermediate:
      +materialized: table
      +schema: esci_intermediate

    marts:
      +materialized: table
      +schema: esci_marts
